#!/bin/bash
#
# NAME
#    svgSplit - program to split an svg into components with the <g> marker
#
# SYNOPSIS 
#    svgSplit [options] file_name
#
# DESCRIPTION 
#    svgSplit is a program that takes an svg as an input.
#    It takes the path inputs for the curves, and splits these 
#    into individual components separated by the <g> marker. 
#    
#    The program must be run with the ./ command from the folder 
#    in which the script resides. The svg must reside in the same
#    folder or be specified with the appopriate path. 
#
#    The following options are available: 
#    -[]  list them here if applicable 
#
#

progname=$(basename "$0") 
file_name=$1
option=""

fatal(){
	echo "$progname: ERROR: $*" >&2
	echo "syntax: $progname file_name [-option]" >&2
	exit 1 
}

# Check if correct number of arguments (1) are provided. 
[ $# -lt 1 ] && fatal "exactly one argument is required"

# Check for options 
# [enter code for options here] 


echo "Here is the revised output for $file_name"

# Create new file 

    touch ./${file_name}.svg

# Read in existing file and copy it to new location 

cat ./butterfly.svg > ./butterfly2.svg

# NOTES AND NEXT STEPS 
# use a loop to identify the sections that draw paths (starts with "<path d=")
# separate each of those into a separate variable
# read in the lines, and separate according to starting with "m" ending with "z"
# need to check how to ignore first 2 (first one starts and second makes entire pattern black)













